### ISSUE TITLE
CO2: Create a summary table by group

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltPolish#3]
> We think now that instead of including the column in the output files, we should provide a table that shows the `co2e_lower` and `co2e_upper` per group, i.e. each value that exists. -- @Tilmon cc' @AnneSchoenauer

**Comment by Tilmon** [comment]
@maurolepore @AnneSchoenauer FYI I updated task description.

**Comment by maurolepore** [comment]
Thanks @Tilmon I'll transfer it to tiltAddCO2 -- which hosts the relevant code.

**Comment by maurolepore** [comment]
@Tilmon here is a reprex showing the summary table. For now focus only on its structure (the correctness of the values is the focus of 2DegreesInvesting/tiltAddCO2#10 and 2DegreesInvesting/tiltAddCO2#12).

* ml01: Is this close to what you expect? 
* ml02: Who is the user of this summary and where would they see it? Do we need to open an issue in tiltWebTool?

``` r
# SETUP

library(tiltToyData)
library(tiltAddCO2)
library(tiltIndicatorAfter)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

# We need the min/max columns
options(tiltIndicatorAfter.output_co2_footprint_min_max = TRUE)
result <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

product <- result |> unnest_product()



# INTERESTING

product |> 
  rename(min_jitter = co2e_lower, max_jitter = co2e_upper) |> 
  summarize_noise(.by = "benchmark")
#> # A tibble: 6 × 3
#>   benchmark           min_noise max_noise
#>   <chr>                   <dbl>     <dbl>
#> 1 all                      31.5     50.0 
#> 2 isic_4digit              66.5      6.63
#> 3 tilt_subsector           42.6    121.  
#> 4 unit                     82.7    135.  
#> 5 unit_isic_4digit         50.4    188.  
#> 6 unit_tilt_subsector      63.3    166.
```

**Comment by Tilmon** [comment]
Hi @maurolepore , 

I was rather thinking of a table that shows the co2e_lower and co2e_upper per each possible value within the benchmarks. To make it more concrete: Instead of showing the average deviation for the `benchmark` == "tilt_subsector", we would need a table that shows the actual `co2_lower `& `co2_upper `for each of the `tilt_subsector`, e.g. for residential construction, land use, chemical industry, etc.. 

To make the intuition behind it clearer, I'll explain an example on how I imagine users to use this table: 
- A user explores the data and sees that the `activity_name` == "apple production" has a "low" emission_profile in the `benchmark` == "tilt_subsector". 
- This is good to know for the user, but the user also wants to better understand which approximate value the co2_footprint of "apple production" has to contextualize the "low" value. 
- To find this out, the user can use the new table you are creating to look up the `co2e_lower` and `co2e_upper` for the combination of `benchmark` == "tilt_subsector" and `tilt_subsector` == "agriculture & livestock". 

@maurolepore note that every `tilt_subsector` should have different `co2e_lower `& `co2e_upper` values even for the same `group_by`. If that's not the case for some reason, we need to see how to proceed. 

Hope that helps!

**Comment by maurolepore** [comment]
@Tilmon if I understand correctly what you're saying is that you want to group not just by `benchmark` but also but `tilt_sector`.

Is this better?

``` r
# SETUP

library(tiltToyData)
library(tiltAddCO2)
library(tiltIndicatorAfter)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

# We need the min/max columns
options(tiltIndicatorAfter.output_co2_footprint_min_max = TRUE)
result <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

product <- result |> unnest_product()



# INTERESTING

group <- c("benchmark", "tilt_subsector")
product |> 
  rename(min_jitter = co2e_lower, max_jitter = co2e_upper) |> 
  summarize_noise(.by = all_of(group))
#> # A tibble: 18 × 4
#>    benchmark           tilt_subsector           min_noise max_noise
#>    <chr>               <chr>                        <dbl>     <dbl>
#>  1 all                 construction residential     70.4       71.5
#>  2 isic_4digit         construction residential     43.3      168. 
#>  3 tilt_subsector      construction residential     62.0      115. 
#>  4 unit                construction residential     68.8       50.4
#>  5 unit_isic_4digit    construction residential     39.7       44.5
#>  6 unit_tilt_subsector construction residential     26.9       95.5
#>  7 all                 other metals                 48.0      161. 
#>  8 isic_4digit         other metals                 52.1       38.6
#>  9 tilt_subsector      other metals                 37.7       51.8
#> 10 unit                other metals                 12.0      116. 
#> 11 unit_isic_4digit    other metals                 86.1       22.6
#> 12 unit_tilt_subsector other metals                  9.06      27.9
#> 13 all                 iron & steel                 71.2      179. 
#> 14 isic_4digit         iron & steel                 68.2       30.5
#> 15 tilt_subsector      iron & steel                 11.1       38.4
#> 16 unit                iron & steel                 70.7       61.4
#> 17 unit_isic_4digit    iron & steel                 26.2      101. 
#> 18 unit_tilt_subsector iron & steel                 26.8      123.
```

<sup>Created on 2024-07-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Tilmon** [comment]
Hi @maurolepore we are almost there :) I just discussed with @AnneSchoenauer and to simplify the output table, let's just show `benchmark` == "tilt_subsector" and then in the column `tilt_subsector` show each tilt_subsector once. 

Also, please instead of the `min_noise` and `max_noise` show the `co2e_lower` and `co2e_upper` columns! 

Does that make sense?

**Comment by Tilmon** [comment]
@maurolepore addendum: Please exclude the noise from the `co2e_lower` & `co2e_upper` columns! :)

**Comment by Tilmon** [comment]
Columns we need: `benchmark`, `tilt_subsector`, `co2e_lower`, `co2e_upper`

**Comment by maurolepore** [comment]
Thanks! 

- [x] just show `benchmark == "tilt_subsector"`
- [x] in the column `tilt_subsector` show each [value only] once.
- [x] instead of the `min_noise` and `max_noise` show `co2e_lower` and `co2e_upper`
- [ ] Ensure the final output has this columns: `benchmark`, `tilt_subsector`, `co2e_lower`, `co2e_upper`

@Tilmon, this reprex checks all the boxes. It seems the data already has the summary we need and we only need to pick the rows and columns you want. 

The last box is unchecked. Currently, the `co2e*` columns currently have noise in them ([changelog](https://2degreesinvesting.github.io/tiltIndicatorAfter/news/index.html?q=co2e#tiltindicatorafter-0009020-2024-02-29)).

> The columns `co2e_lower` and `co2e_upper` show the lowest and highest value of `co2_footprint` within the group to which the product was compared, plus some randomness ([helpfile](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html#value))

In the reprex the values you want I think are the ones under `min` and `max`.

So if I understand correctly, what you are asking for is to assign the (unjittered) `min` summary to `co2e_lower` and the (unjittered) `max` summary to `co2e_upper`. Right?

That can be confusing since the internal logic still hods jittered values in the `co2e*` columns (we can and should refactor this but would take longer so maybe not for now). Ideally we would come up with a different name that still makes us happy, e.g. `co2_min` and `co2_max`. 

In any case, we'll need to check with Kalash since we may be using those exact column names in particular ways. (I'm not tagging him yet until we clarify that we really need his input).

``` r
# SETUP

library(tiltToyData)
library(tiltAddCO2)
library(tiltIndicatorAfter)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

# We need the min/max columns
options(tiltIndicatorAfter.output_co2_footprint_min_max = TRUE)
result <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

product <- result |> unnest_product()



# INTERESTING

# mim/max are already a summary, so all we need is to subset the relevant data
# see `?tiltIndicator::summarize_range()`, i.e. the min() and max() of
# `co2_footprint`, and it's grouped by the relevant columns
group <- c("benchmark", "tilt_subsector")
product |> 
  filter(benchmark == "tilt_subsector") |> 
  select(matches(c("benchmark|tilt_subsector|min$|max$|co2e"))) |> 
  # should be unnecessary but just in case
  distinct()
#> # A tibble: 3 × 6
#>   benchmark      tilt_subsector               min     max co2e_lower co2e_upper
#>   <chr>          <chr>                      <dbl>   <dbl>      <dbl>      <dbl>
#> 1 tilt_subsector construction residential 303.    303.      -109.        476.  
#> 2 tilt_subsector other metals               0.693   0.693      0.477       1.02
#> 3 tilt_subsector iron & steel              10.4    10.4        1.78       16.2
```

<sup>Created on 2024-07-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Tilmon** [comment]
Hi @maurolepore , 

cool, seems indeed like `min` and `max` show the values we are looking for, i.e. the lowest and the highest `co2_footprint `within the group, correct? 

**ml 01:** 

> In the reprex the values you want I think are the ones under min and max.
> 
> So if I understand correctly, what you are asking for is to assign the (unjittered) min summary to co2e_lower and the (unjittered) max summary to co2e_upper. Right?

Not sure I correctly understand what you mean with "assign the min summary to co2e_lower [...]"... Does the folloing answer your question? I think we can just use the column `min` and `max` instead of `co2e_lower` and `co2e_upper`, if I'm correctly assuming that they show the lowest and highest `co2_footprint` value for each group. 

> That can be confusing since the internal logic still hods jittered values in the co2e* columns (we can and should refactor this but would take longer so maybe not for now). Ideally we would come up with a different name that still makes us happy, e.g. co2_min and co2_max.

Re naming of the column: Here I don't really care how to best name the column, feel free to choose a name most suitable for you (in case you don't want to keep the name `min` and `max`). 

As I said, we'll show the table only in a static version in the _tilt_ documentation, so we can always adjust column names in that table :)

**Comment by Tilmon** [comment]
@maurolepore if the following is correct

> min and max show the values we are looking for, i.e. the lowest and the highest co2_footprint within the group. 

then I think you can change the requiremen the fourth bullet point in your comment (2DegreesInvesting/tiltPolish#3#issuecomment-2231391904) from  "the final output has this columns: benchmark, tilt_subsector, co2e_lower, co2e_upper" to "the final output has this columns: benchmark, tilt_subsector, min, max"

**Comment by maurolepore** [comment]
Thanks @Tilmon then the final output would look like this:


```r
#> # A tibble: 3 × 4
#>   benchmark      tilt_subsector               min     max
#>   <chr>          <chr>                      <dbl>   <dbl>
#> 1 tilt_subsector construction residential 303.    303.   
#> 2 tilt_subsector other metals               0.693   0.693
#> 3 tilt_subsector iron & steel              10.4    10.4
```

<details>

``` r
# SETUP

library(tiltToyData)
library(tiltAddCO2)
library(tiltIndicatorAfter)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

# We need the min/max columns
options(tiltIndicatorAfter.output_co2_footprint_min_max = TRUE)
result <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

product <- result |> unnest_product()



# INTERESTING

group <- c("benchmark", "tilt_subsector")
product |> 
  filter(benchmark == "tilt_subsector") |> 
  select(matches(c("benchmark|tilt_subsector|min$|max$"))) |> 
  # should be unnecessary but just in case
  distinct()
#> # A tibble: 3 × 4
#>   benchmark      tilt_subsector               min     max
#>   <chr>          <chr>                      <dbl>   <dbl>
#> 1 tilt_subsector construction residential 303.    303.   
#> 2 tilt_subsector other metals               0.693   0.693
#> 3 tilt_subsector iron & steel              10.4    10.4
```

<sup>Created on 2024-07-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


</details>

And this checks all our boxes. Thanks! 

- [x] just show `benchmark == "tilt_subsector"`
- [x] in the column `tilt_subsector` show each [value only] once.
- [x] instead of the `min_noise` and `max_noise` show `co2e_lower` and `co2e_upper`
- [x] Ensure the final output has this columns: `benchmark`, `tilt_subsector`, `min`, `max`.

**Comment by Tilmon** [comment]
@maurolepore great, thanks! Just to be clear: You confirm, that `min` and `max` show the lowest and highest co2_footprint value for each group (i.e., for every `benchmark`-`til_subsector `combination in our case here) , right?

**Comment by maurolepore** [comment]
Correct @Tilmon, I confirm that.

**Comment by maurolepore** [comment]
@Tilmon FYI the new feature is here

https://2degreesinvesting.github.io/tiltPolish/#example

**Comment by Tilmon** [comment]
@maurolepore great, thanks! Once the new data are created (2DegreesInvesting/tiltOutput#7), can you already apply the function to that data and provide @AnneSchoenauer and myself with the output table please?

**Comment by maurolepore** [comment]
Sure

* https://github.com/2DegreesInvesting/tiltOutput/issues/6
